import Head from "next/head";
import Navbar from "../components/index/navbar";
import Main from "../components/index/main";
import Footer from "../components/footer";


export default function Home() {

  return (
    <>
      <Head>
        <title>Inicio-Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ICONO.ico" />
      </Head>

      <Navbar />

      <header>
        <div className="header-container">
          <div className="description"></div>
          <div className="foto"></div>
        </div>
        <div className="aboutMy">
          <div className="aboutMy-title"></div>
          <div className="aboutMy-description"></div>
        </div>
      </header>

      <main>
        <Main page = "main"></Main>
      </main>

      <Footer></Footer>
    </>
  );
}
