import Head from "next/head";
import Navbar from "../components/index/navbar";
import Footer from "../components/footer";
import AboutMe from "../components/index/aboutMe";
import LayoutComponents from "../components/layoutComponents";

import stl from "../styles/index.module.scss";
import { globalContext } from "../context/global/globalState";
import { useContext, useEffect } from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Inicio-Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ICONO.ico" />
      </Head>

      <Navbar />

      <header className={stl.header}>
        <AboutMe />
      </header>

      <main className={stl.main}>
        <Main page="main"></Main>
      </main>
      <div className={stl.up}>
        <a href="#nav">subir ^</a>
      </div>

      <Footer></Footer>
    </>
  );
}

const Main = ({ typePage }) => {
  const { pages } = useContext(globalContext);
  return (
    <>
      {pages
        ? pages.map(page => (
            <LayoutComponents
              title={`${page.title}`}
              type={page.type}
              page={typePage}
              key={`${page.type}`}
            />
          ))
        : null}
    </>
  );
};
